### ISSUE TITLE
blog

### ISSUE THREAD

**Issue by OlgaLu** [alexalexyang/olga#5]
i want blog page to be looking like it looks now here https://olga.notathoughtexperiment.me/blog/

but when i add blog posts in the dashboard, it automatically puts it on the blog page
like this test "lknlkn"
![image](https://user-images.githubusercontent.com/38591021/40783793-dbe1d350-64e3-11e8-806d-2969459fb2c2.png)

 
I would still like to have a tags system and use dashboard for blog posts
but i would like to control main blog page manually and link posts to it

**Comment by alexalexyang** [comment]
settled off github.
