### ISSUE TITLE
buttons

### ISSUE THREAD

**Issue by OlgaLu** [alexalexyang/olga#8]
I can't find how to style "checkout now" button
I do it writing new bits in custom.css, but it strangely seems not to overwrite the bootstrap-theme.min.css

![image](https://user-images.githubusercontent.com/38591021/41320036-50ac8978-6e9e-11e8-81af-47280225fc14.png)

generally, I'd remove buttons styling from bootstrap-theme.min.css and bootstrap.min.css - it constantly leaves artefacts like flashing colour when you click, etc

**Comment by alexalexyang** [comment]
this was complicated because of the different style sheets. on hindsight, we should have edited on style.css directly. anyway i sort of fixed this. you may want to play with it a bit more. in custom.css:

```
.btn-primary:focus, .btn-primary:hover, .btn-primary:active, .btn-primary:active:hover {
    background-color: #cccccc52;
    border-color: #cccccc52;
}

.btn-info, .btn-info:focus, .btn-info:hover, .btn-info:active, .btn-info:active:hover {
    background-color: #cccccc52;
    border-color: #cccccc52;
    background-image: none;
    text-shadow: none;
}
```
