### ISSUE TITLE
blog post

### ISSUE THREAD

**Issue by OlgaLu** [alexalexyang/olga#9]
I want to make blog posts not full screen, but a bit narrower.
I think I've managed with the body, but can't figure out how to change the padding of the title

The title should be similar to this:
.editable-original {
  padding-left: 100px;
  padding-right: 100px;
  margin-left: auto;
  margin-right: auto;
  min-width: 350px;
}

+ not critical, but if we can easily remove metadata, I'd prefer not to have it (posted by line)
 
![image](https://user-images.githubusercontent.com/38591021/41436763-4fb9ca60-702b-11e8-9313-0509b56f5721.png)

**Comment by OlgaLu** [comment]
oooops, changing .editable-original was a bad idea...
ok, i'll introduce .blog_text for the body of it

but the task is to remove "posted by" and move the title either to the center or 100px padding from left and right

**Comment by alexalexyang** [comment]
the html template is at \olga\templates\blog\blog_post_detail.html

try editing that?

**Comment by alexalexyang** [comment]
"posted by" removed. and i think you fixed the padding.
